"""Read-only database metadata public API."""

from __future__ import annotations

from repo_graph.database._metadata import (
    CURRENT_DATABASE_SCHEMA_STATE,
    POSTGRES_ENGINE,
    POSTGRES_METADATA_PARSER,
    SQLSERVER_ENGINE,
    SQLSERVER_METADATA_PARSER,
    DatabaseScanResult,
    DatabaseSourceRequest,
    PostgresDependencyRow,
    PostgresForeignKeyRow,
    PostgresMetadata,
    PostgresObjectRow,
    PostgresTriggerRow,
    SqlServerDependencyRow,
    SqlServerForeignKeyRow,
    SqlServerMetadata,
    SqlServerObjectRow,
    SqlServerTriggerRow,
    database_connector_unavailable_message,
    database_metadata_adapter,
    normalize_database_engine,
    postgres_driver_available,
    scan_database_metadata,
    scan_database_source,
    scan_postgres_metadata,
    scan_postgres_source,
    scan_sqlserver_metadata,
    scan_sqlserver_source,
    sqlserver_driver_available,
    supported_database_engines,
)

__all__ = [
    "CURRENT_DATABASE_SCHEMA_STATE",
    "POSTGRES_ENGINE",
    "POSTGRES_METADATA_PARSER",
    "SQLSERVER_ENGINE",
    "SQLSERVER_METADATA_PARSER",
    "DatabaseScanResult",
    "DatabaseSourceRequest",
    "PostgresDependencyRow",
    "PostgresForeignKeyRow",
    "PostgresMetadata",
    "PostgresObjectRow",
    "PostgresTriggerRow",
    "SqlServerDependencyRow",
    "SqlServerForeignKeyRow",
    "SqlServerMetadata",
    "SqlServerObjectRow",
    "SqlServerTriggerRow",
    "database_connector_unavailable_message",
    "database_metadata_adapter",
    "normalize_database_engine",
    "postgres_driver_available",
    "scan_database_metadata",
    "scan_database_source",
    "scan_postgres_metadata",
    "scan_postgres_source",
    "scan_sqlserver_metadata",
    "scan_sqlserver_source",
    "sqlserver_driver_available",
    "supported_database_engines",
]
