"""HTTP API public surface for Repo Graph."""

from __future__ import annotations

from repo_graph.api_runtime.config_workflows import (
    build_load_response,
    build_response,
    config_response,
    configured_sources_response,
    job_response,
    jobs_response,
    load_response,
    mapping_value,
    refresh_changed_response,
    refresh_response,
    snapshot_changed_source_names,
    snapshot_status_response,
    submit_build_job,
    submit_build_load_job,
    submit_refresh_changed_job,
    submit_refresh_job,
    submit_snapshot_status_job,
    submit_sync_job,
    sync_response,
)
from repo_graph.api_runtime.coverage import (
    coverage_classification_warnings,
    coverage_edge_type_warnings,
    coverage_severity_rank,
    coverage_warning,
    coverage_warnings_for_entity_source,
    coverage_warnings_from_report,
)
from repo_graph.api_runtime.errors import neo4j_http_exception
from repo_graph.api_runtime.manifest import health_payload, manifest_payload, ui_index_path
from repo_graph.api_runtime.query_responses import (
    add_optional_filter,
    entity_overview_response,
    entity_response,
    explore_response,
    impact_response,
    neighbors_response,
    relationship_filters_payload,
    relationship_search_response,
    scope_response,
    search_entities_response,
    source_overview_response,
    sources_response,
    unresolved_edges_response,
)
from repo_graph.api_runtime.relationships import (
    add_if_string,
    min_depth,
    relationship_evidence_groups,
    relationship_groups,
    relationship_neighbor_type,
    relationship_source_name,
    string_mapping_value,
)
from repo_graph.api_runtime.report_responses import (
    database_reconciliation_report_response,
    interactions_report_response,
    unresolved_report_response,
)
from repo_graph.api_runtime.requests import (
    BuildLoadRequest,
    BuildRequest,
    LoadRequest,
    RefreshChangedRequest,
    RefreshRequest,
    SnapshotStatusRequest,
    SyncRequest,
)
from repo_graph.api_runtime.routes import create_app
from repo_graph.api_runtime.settings import (
    RuntimeSettings,
    default_graph_path,
    env_path,
    env_value,
    load_runtime_config,
    resolve_config_path,
    resolve_graph_path,
    validate_max_file_bytes,
)
from repo_graph.api_runtime.source_files import (
    normalize_snippet_context,
    normalize_snippet_line,
    read_snippet_lines,
    required_non_empty,
    safe_source_file_path,
    source_file_snippet_response,
    source_root_from_config,
    source_root_from_loaded_graph,
    source_root_path,
)

app = create_app()

__all__ = [
    "BuildLoadRequest",
    "BuildRequest",
    "LoadRequest",
    "RefreshChangedRequest",
    "RefreshRequest",
    "RuntimeSettings",
    "SnapshotStatusRequest",
    "SyncRequest",
    "add_if_string",
    "add_optional_filter",
    "app",
    "build_load_response",
    "build_response",
    "config_response",
    "configured_sources_response",
    "coverage_classification_warnings",
    "coverage_edge_type_warnings",
    "coverage_severity_rank",
    "coverage_warning",
    "coverage_warnings_for_entity_source",
    "coverage_warnings_from_report",
    "create_app",
    "database_reconciliation_report_response",
    "default_graph_path",
    "entity_overview_response",
    "entity_response",
    "env_path",
    "env_value",
    "explore_response",
    "health_payload",
    "impact_response",
    "interactions_report_response",
    "job_response",
    "jobs_response",
    "load_response",
    "load_runtime_config",
    "manifest_payload",
    "mapping_value",
    "min_depth",
    "neighbors_response",
    "neo4j_http_exception",
    "normalize_snippet_context",
    "normalize_snippet_line",
    "read_snippet_lines",
    "refresh_changed_response",
    "refresh_response",
    "relationship_evidence_groups",
    "relationship_filters_payload",
    "relationship_groups",
    "relationship_neighbor_type",
    "relationship_search_response",
    "relationship_source_name",
    "required_non_empty",
    "resolve_config_path",
    "resolve_graph_path",
    "safe_source_file_path",
    "scope_response",
    "search_entities_response",
    "snapshot_changed_source_names",
    "snapshot_status_response",
    "source_file_snippet_response",
    "source_overview_response",
    "source_root_from_config",
    "source_root_from_loaded_graph",
    "source_root_path",
    "sources_response",
    "string_mapping_value",
    "submit_build_job",
    "submit_build_load_job",
    "submit_refresh_changed_job",
    "submit_refresh_job",
    "submit_snapshot_status_job",
    "submit_sync_job",
    "sync_response",
    "ui_index_path",
    "unresolved_edges_response",
    "unresolved_report_response",
    "validate_max_file_bytes",
]
