"""Graph edge vocabulary."""

from __future__ import annotations

EDGE_TYPES = (
    "CALLS_HTTP",
    "CALLS_SERVICE",
    "CALLS_SQL",
    "CALLS_SYMBOL",
    "CONFIGURES_SERVICE",
    "CONSUMES_MESSAGE",
    "CONTAINS_FILE",
    "CONTAINS_PROJECT",
    "DECLARES_BUILD_CONFIG",
    "DECLARES_CONFIG",
    "DECLARES_CONFIG_FILE",
    "DECLARES_DEPLOYMENT",
    "DECLARES_INGRESS",
    "DECLARES_JOB",
    "DECLARES_PACKAGE",
    "DECLARES_ROUTE",
    "DECLARES_SERVICE",
    "DECLARES_SOLUTION",
    "DECLARES_SYMBOL",
    "DECLARES_WORKSPACE",
    "DEFINES",
    "DEPENDS_ON_PACKAGE",
    "DEPENDS_ON_PROJECT",
    "EXPOSES_ROUTE",
    "HANDLES_ROUTE",
    "IMPORTS",
    "PUBLISHES_MESSAGE",
    "READS_CACHE_KEY",
    "READS_SQL_OBJECT",
    "READS_STORAGE_OBJECT",
    "REFERENCES_SQL_OBJECT",
    "ROUTES_TO_SERVICE",
    "RUNS_CONTAINER",
    "RUNS_JOB",
    "SCHEDULES_JOB",
    "SELECTS_DEPLOYMENT",
    "TRIGGERS_ON_SQL_OBJECT",
    "WRITES_SQL_OBJECT",
    "WRITES_STORAGE_OBJECT",
    "WRITES_CACHE_KEY",
)
SQL_EDGE_TYPES = frozenset(
    {"CALLS_SQL", "READS_SQL_OBJECT", "REFERENCES_SQL_OBJECT", "TRIGGERS_ON_SQL_OBJECT", "WRITES_SQL_OBJECT"}
)
INTERACTION_EDGE_TYPES = frozenset(
    {
        "CALLS_HTTP",
        "CALLS_SERVICE",
        "CALLS_SQL",
        "CONFIGURES_SERVICE",
        "CONSUMES_MESSAGE",
        "PUBLISHES_MESSAGE",
        "READS_CACHE_KEY",
        "READS_SQL_OBJECT",
        "READS_STORAGE_OBJECT",
        "REFERENCES_SQL_OBJECT",
        "ROUTES_TO_SERVICE",
        "TRIGGERS_ON_SQL_OBJECT",
        "WRITES_SQL_OBJECT",
        "WRITES_STORAGE_OBJECT",
        "WRITES_CACHE_KEY",
    }
)
