"""API runtime constants."""

from __future__ import annotations

from pathlib import Path

DEFAULT_CONFIG_PATH = Path("config/local-example.yaml")
DEFAULT_NEO4J_URI = "bolt://neo4j:7687"
DEFAULT_NEO4J_PASSWORD = "repo-graph-password"
UNRESOLVED_REPORT_EDGE_LIMIT = 1000
INTERACTION_REPORT_EDGE_LIMIT = 1000
DATABASE_RECONCILIATION_EDGE_LIMIT = 1000
DATABASE_RECONCILIATION_ENTITY_LIMIT = 1000
SOURCE_SNIPPET_MAX_CONTEXT = 50
SOURCE_SNIPPET_MAX_BYTES = 1_000_000
UI_DIR = Path(__file__).parent.parent / "ui"

__all__ = [
    "DATABASE_RECONCILIATION_EDGE_LIMIT",
    "DATABASE_RECONCILIATION_ENTITY_LIMIT",
    "DEFAULT_CONFIG_PATH",
    "DEFAULT_NEO4J_PASSWORD",
    "DEFAULT_NEO4J_URI",
    "INTERACTION_REPORT_EDGE_LIMIT",
    "SOURCE_SNIPPET_MAX_BYTES",
    "SOURCE_SNIPPET_MAX_CONTEXT",
    "UI_DIR",
    "UNRESOLVED_REPORT_EDGE_LIMIT",
]
