"""Source resolver compatibility facade."""

from __future__ import annotations

from repo_graph.sources._expansion import expand_one_source, expand_sources
from repo_graph.sources._git import (
    checkout_branch,
    checkout_ref,
    get_default_branch,
    git_command_env,
    git_commit,
    git_origin_url,
    git_ref_exists,
    git_repo_present,
    git_symbolic_ref,
    next_git_config_index,
    redact_github_token,
    run_git,
    safe_git_origin_url,
    sync_git_source,
)
from repo_graph.sources._github import (
    github_api_get,
    github_api_headers,
    github_api_pages,
    github_git_auth_header,
    github_next_link,
    github_org_repositories,
    github_org_sources,
    github_repo_name,
    github_repo_selected,
    github_repo_url,
    github_token,
)
from repo_graph.sources._models import ResolvedSource
from repo_graph.sources._paths import git_cache_path, safe_path_name, source_path
from repo_graph.sources._resolution import resolve_expanded_sources, resolve_sources
from repo_graph.sources._status import (
    config_summary,
    configured_source_payload,
    database_source_problems,
    inspect_sources,
    source_expansion_failure_status,
    source_problems,
    source_ready,
    source_status,
    sync_sources_with_status,
)
from repo_graph.sources._sync import sync_one_source, sync_sources

__all__ = [
    "ResolvedSource",
    "checkout_branch",
    "checkout_ref",
    "config_summary",
    "configured_source_payload",
    "database_source_problems",
    "expand_one_source",
    "expand_sources",
    "get_default_branch",
    "git_cache_path",
    "git_command_env",
    "git_commit",
    "git_origin_url",
    "git_ref_exists",
    "git_repo_present",
    "git_symbolic_ref",
    "github_api_get",
    "github_api_headers",
    "github_api_pages",
    "github_git_auth_header",
    "github_next_link",
    "github_org_repositories",
    "github_org_sources",
    "github_repo_name",
    "github_repo_selected",
    "github_repo_url",
    "github_token",
    "inspect_sources",
    "next_git_config_index",
    "redact_github_token",
    "resolve_expanded_sources",
    "resolve_sources",
    "run_git",
    "safe_git_origin_url",
    "safe_path_name",
    "source_expansion_failure_status",
    "source_path",
    "source_problems",
    "source_ready",
    "source_status",
    "sync_git_source",
    "sync_one_source",
    "sync_sources",
    "sync_sources_with_status",
]
