"""C# and VB code scanner helper facade."""

from __future__ import annotations

from repo_graph.extraction.scanners.code.dotnet.csharp_interactions import CS_HTTP_CALL_RE, csharp_http_call_facts
from repo_graph.extraction.scanners.code.dotnet.csharp_routes import (
    CS_MINIMAL_ROUTE_RE,
    csharp_controller_route_facts,
    csharp_http_attribute_method,
    csharp_minimal_route_facts,
    csharp_route_prefix,
)
from repo_graph.extraction.scanners.code.dotnet.csharp_symbols import (
    CS_DIRECT_METHOD_CALL_RE,
    CS_METHOD_RE,
    CS_NEW_METHOD_CALL_RE,
    CS_QUALIFIED_METHOD_CALL_RE,
    CS_TYPE_RE,
    csharp_direct_method_call_targets,
    csharp_entity_type,
    csharp_method_index,
    csharp_new_method_call_targets,
    csharp_qualified_method_call_targets,
    csharp_symbol_call_facts,
    csharp_symbol_facts,
)
from repo_graph.extraction.scanners.code.dotnet.csharp_syntax import (
    CS_ATTRIBUTE_ITEM_RE,
    CS_ATTRIBUTE_LINE_RE,
    CS_NAMESPACE_RE,
    CSharpAttribute,
    csharp_attribute_name,
    csharp_attributes,
    csharp_first_string,
    csharp_function_scope_state,
    csharp_join_route_paths,
    csharp_replace_route_tokens,
    csharp_scope_code,
    csharp_should_clear_attributes,
    csharp_unescape_string,
)
from repo_graph.extraction.scanners.code.dotnet.vb_interactions import (
    VB_COMMAND_TEXT_RE,
    VB_CONFIG_SETTING_RE,
    VB_HTTP_LITERAL_RE,
    VB_SQL_COMMAND_RE,
    legacy_http_client,
    legacy_http_facts_for_target,
    vb_service_call_facts,
    vb_sql_command_facts,
)
from repo_graph.extraction.scanners.code.dotnet.vb_routes import (
    legacy_contract_framework,
    legacy_dotnet_service_path,
    vb_contract_route_facts,
)
from repo_graph.extraction.scanners.code.dotnet.vb_symbols import (
    VB_DIRECT_METHOD_CALL_RE,
    VB_NEW_METHOD_CALL_RE,
    VB_QUALIFIED_METHOD_CALL_RE,
    vb_direct_method_call_targets,
    vb_method_index,
    vb_new_method_call_targets,
    vb_qualified_method_call_targets,
    vb_symbol_call_facts,
    vb_symbol_facts,
)
from repo_graph.extraction.scanners.code.dotnet.vb_syntax import (
    VB_ATTRIBUTE_RE,
    VB_END_METHOD_RE,
    VB_METHOD_RE,
    VB_NAMESPACE_RE,
    VB_TYPE_RE,
    vb_scope_code,
)

__all__ = [
    "CS_ATTRIBUTE_ITEM_RE",
    "CS_ATTRIBUTE_LINE_RE",
    "CS_DIRECT_METHOD_CALL_RE",
    "CS_HTTP_CALL_RE",
    "CS_METHOD_RE",
    "CS_MINIMAL_ROUTE_RE",
    "CS_NAMESPACE_RE",
    "CS_NEW_METHOD_CALL_RE",
    "CS_QUALIFIED_METHOD_CALL_RE",
    "CS_TYPE_RE",
    "VB_ATTRIBUTE_RE",
    "VB_COMMAND_TEXT_RE",
    "VB_CONFIG_SETTING_RE",
    "VB_DIRECT_METHOD_CALL_RE",
    "VB_END_METHOD_RE",
    "VB_HTTP_LITERAL_RE",
    "VB_METHOD_RE",
    "VB_NAMESPACE_RE",
    "VB_NEW_METHOD_CALL_RE",
    "VB_QUALIFIED_METHOD_CALL_RE",
    "VB_SQL_COMMAND_RE",
    "VB_TYPE_RE",
    "CSharpAttribute",
    "csharp_attribute_name",
    "csharp_attributes",
    "csharp_controller_route_facts",
    "csharp_direct_method_call_targets",
    "csharp_entity_type",
    "csharp_first_string",
    "csharp_function_scope_state",
    "csharp_http_attribute_method",
    "csharp_http_call_facts",
    "csharp_join_route_paths",
    "csharp_method_index",
    "csharp_minimal_route_facts",
    "csharp_new_method_call_targets",
    "csharp_qualified_method_call_targets",
    "csharp_replace_route_tokens",
    "csharp_route_prefix",
    "csharp_scope_code",
    "csharp_should_clear_attributes",
    "csharp_symbol_call_facts",
    "csharp_symbol_facts",
    "csharp_unescape_string",
    "legacy_contract_framework",
    "legacy_dotnet_service_path",
    "legacy_http_client",
    "legacy_http_facts_for_target",
    "vb_contract_route_facts",
    "vb_direct_method_call_targets",
    "vb_method_index",
    "vb_new_method_call_targets",
    "vb_qualified_method_call_targets",
    "vb_scope_code",
    "vb_service_call_facts",
    "vb_sql_command_facts",
    "vb_symbol_call_facts",
    "vb_symbol_facts",
]
